# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcquiredFrom',
            fields=[
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apperance',
            fields=[
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('summary', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OriginCode',
            fields=[
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SampleCode',
            fields=[
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubstanceSurvey',
            fields=[
                ('added', models.DateField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_acquired', models.DateField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=255)),
                ('sample_code', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='substances')),
                ('observations', models.TextField(blank=True)),
                ('acquired_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.AcquiredFrom')),
                ('alias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Alias')),
                ('apperance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Apperance')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.City')),
                ('color', models.ManyToManyField(blank=True, to='survey.Color')),
                ('detected', models.ManyToManyField(blank=True, to='survey.Drug')),
                ('kinds', models.ManyToManyField(blank=True, to='survey.Kind')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Origin')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Region')),
                ('substance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Substance')),
            ],
            options={
                'ordering': ['-added'],
            },
        ),
        migrations.CreateModel(
            name='TestMethod',
            fields=[
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCode',
            fields=[
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='substancesurvey',
            name='testmethods',
            field=models.ManyToManyField(blank=True, to='survey.TestMethod'),
        ),
        migrations.AddField(
            model_name='substancesurvey',
            name='user_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.UserCode'),
        ),
    ]
