# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginCode',
            fields=[
                ('code', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserCode',
        ),
        migrations.RemoveField(
            model_name='apperance',
            name='id',
        ),
        migrations.RemoveField(
            model_name='city',
            name='id',
        ),
        migrations.RemoveField(
            model_name='color',
            name='id',
        ),
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.RemoveField(
            model_name='kind',
            name='id',
        ),
        migrations.RemoveField(
            model_name='origin',
            name='id',
        ),
        migrations.RemoveField(
            model_name='source',
            name='id',
        ),
        migrations.RemoveField(
            model_name='substancesurvey',
            name='id',
        ),
        migrations.RemoveField(
            model_name='substancesurvey',
            name='user_code',
        ),
        migrations.RemoveField(
            model_name='testmethod',
            name='id',
        ),
        migrations.AddField(
            model_name='substancesurvey',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='apperance',
            name='name',
            field=models.CharField(editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='kind',
            name='name',
            field=models.CharField(editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='origin',
            name='name',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='testmethod',
            name='name',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='substancesurvey',
            name='origin_code',
            field=models.ForeignKey(blank=True, default='AZ23948', on_delete=django.db.models.deletion.CASCADE, to='survey.OriginCode'),
            preserve_default=False,
        ),
    ]
