# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20171024_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substancesurvey',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
