# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20171024_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substancesurvey',
            name='image',
            field=models.ImageField(blank=True, upload_to='substances'),
        ),
        migrations.AlterField(
            model_name='substancesurvey',
            name='substance',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
