# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20171024_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='substancesurvey',
            options={'ordering': ['-added']},
        ),
    ]
