# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20171024_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substancesurvey',
            name='added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
