# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20171025_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='substancesurvey',
            old_name='kind',
            new_name='kinds',
        ),
        migrations.RenameField(
            model_name='substancesurvey',
            old_name='test_methods',
            new_name='testmethods',
        ),
    ]
