# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-03 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('content', models.TextField(help_text="You can use <a href='http://commonmark.org/help/'>MarkDown</a> formatting", verbose_name='Content')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('meta_description', models.TextField(blank=True, max_length=500, verbose_name='SEO: Meta description')),
            ],
            options={
                'verbose_name': 'Static Page',
                'verbose_name_plural': 'Static Pages',
            },
        ),
    ]
